# Generated by Django 5.0.1 on 2024-04-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_rename_titile_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="LOW",
                max_length=31,
            ),
        ),
    ]
