# Generated by Django 5.0.1 on 2024-04-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0007_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[(1, "High"), (3, "Medium"), (2, "Low")],
                default=1,
                max_length=31,
            ),
        ),
    ]
