# Generated by Django 5.0.1 on 2024-04-13 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0019_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="creator",
        ),
    ]
