# Generated by Django 5.0.1 on 2024-04-20 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0021_task_task_for"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-create_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["priority", "due_to_date"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="comment_media"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_for",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
